"""
Types for air quality API data
"""

DEATH_TYPES = [
    "grand total",
    "certain infectious and parasitic diseases total",
    "certain infectious and parasitic diseases - AIDS",
    "neoplasms, total",
    "malignant neoplasms total",
    "cancer of the stomach, colon, rectum, bowel and rectum connectors",
    "cancer of the trachea, bronchus and lung",
    "female breast cancer and cervical cancer",
    "diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism",
    "endocrine, nutritional and metabolic diseases, total",
    "Endocrine, nutritional and metabolic diseases",
    "mental and behavioural disorders",
    "Diseases of the nervous system and sense organs",
    "diseases of the circulatory system, total",
    "Diseases of the circulatory system - hypertensive disease",
    "Diseases of the circulatory system - ischaemic heart disease",
    "Diseases of the circulatory system - cerebrovascular disease",
    "Diseases of the circulatory system - atherosclerotic vascular",
    "diseases of the respiratory system, total",
    "respiratory diseases - pneumonia, bronchitis, emphysema and asthma",
    "diseases of the digestive system, total",
    "digestive system diseases - chronic disease and liver cirrhosis",
    "Diseases of the skin and subcutaneous",
    "diseases of the musculoskeletal system and connective tissue",
    "diseases of the genitourinary system",
    "Pregnancy, childbirth and the puerperium",
    "certain conditions originating in the perinatal period",
    "congenital malformations, deformations and chromosomal abnormalities",
    "symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified",
    "external causes of morbidity and mortality, total",
    "External causes of morbidity and mortality - the consequences of accidents and unfortunate incidents - total",
    "other external causes of accident injurie - traffic accidents, total",
    "External causes of morbidity and mortality - consequences of accidents and unfortunate incidents - traffic accidents- accidents in motor vehicles",
    "other external causes of accident injurie",
    "suicide",
    "homicide",
    "cause of death (description) missing from the statistic card annexed to the death certificate",
    "COVID-19",
]


REGIONS = [
    "MAŁOPOLSKIE",
    "ŚLĄSKIE",
    "LUBUSKIE",
    "WIELKOPOLSKIE",
    "ZACHODNIOPOMORSKIE",
    "DOLNOŚLĄSKIE",
    "OPOLSKIE",
    "KUJAWSKO-POMORSKIE",
    "POMORSKIE",
    "WARMIŃSKO-MAZURSKIE",
    "ŁÓDZKIE",
    "ŚWIĘTOKRZYSKIE",
    "LUBELSKIE",
    "PODKARPACKIE",
    "PODLASKIE",
    "MAZOWIECKIE",
]
