---
- name: Base system setup
  hosts: ubuntu
  become: true
  roles:
    - common
    - docker
    - xrdp

- name: Installing default browser
  hosts: ubuntu
  become: true
  roles:
    - browser

- name: Application setup
  hosts: ubuntu
  become: true
  roles:
    - app

- name: Configuration setup
  hosts: ubuntu
  become: true
  roles:
    - config

- name: Service deployment
  hosts: ubuntu
  become: true
  roles:
    - deploy
