all:
  children:
    ubuntu:
      hosts:
        vm-ubuntu-smogsense:
          ansible_host: "{{ lookup('env', 'ANSIBLE_HOST') }}"
          ansible_user: "{{ lookup('env', 'TF_VAR_admin_username') }}"
          ansible_password: "{{ lookup('env', 'TF_VAR_admin_password') }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_PRIVATE_KEY_FILE') }}"
