- name: Update apt cache
  apt:
    update_cache: yes

- name: Install core dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - git
    state: present
